### ISSUE TITLE
Plugin has no effect on WordPress 6.2.2

### ISSUE THREAD

**Issue by lourot** [dracula/wordpress#10]
For me, activating the plugin on WordPress 6.2.2 has no effect. No color changes in my Admin panel. This is **not** caused by #7. I tried the version just before and have the same problem.

**Comment by rdelbem** [comment]
Hey,
This plugin creates a new color schema option in the user profile page. So, it is necessary, after plugin is activated, to take further action. Go to Users > Profile > Admin Color Scheme > Dracula > click Update Profile.
Since this is the second time an issue is created addressing the lack of changes after plugin activation, I think maybe we could display a toast or a message asserting the need to make this change. Or, maybe, change it programmatically after the plugin is activated.
WDYT?
https://drive.google.com/file/d/1uQUOenyQaE3Q48LaPq6rcet2IDgvUmDL/view?usp=sharing

**Comment by lourot** [comment]
Thank you for clarifying and for #11 :pray: It's very clear now
